// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/Author.ts";
import * as $$$4 from "./loaders/Blogpost.ts";
import * as $$$1 from "./loaders/BlogPostItem.ts";
import * as $$$5 from "./loaders/BlogpostList.ts";
import * as $$$6 from "./loaders/BlogpostListing.ts";
import * as $$$2 from "./loaders/BlogPostPage.ts";
import * as $$$3 from "./loaders/BlogRelatedPosts.ts";
import * as $$$7 from "./loaders/Category.ts";
import * as $$$8 from "./loaders/ContentTypes.ts";
import * as $$$9 from "./loaders/GetCategories.ts";
import * as $$$$$$0 from "./sections/Blog/components/ImageAndTextSection.tsx";
import * as $$$$$$3 from "./sections/Blog/components/ImagesSlide.tsx";
import * as $$$$$$1 from "./sections/Blog/components/ImageThreeColumnSection.tsx";
import * as $$$$$$2 from "./sections/Blog/components/ImageTwoColumnSection.tsx";
import * as $$$$$$4 from "./sections/Blog/components/OneImage.tsx";
import * as $$$$$$5 from "./sections/Blog/components/ProductsSection.tsx";
import * as $$$$$$6 from "./sections/Blog/components/RelatedPosts.tsx";
import * as $$$$$$7 from "./sections/Blog/components/TextSection.tsx";
import * as $$$$$$8 from "./sections/Blog/components/Video.tsx";
import * as $$$$$$9 from "./sections/BlogBannerPost.tsx";
import * as $$$$$$10 from "./sections/BlogPosts.tsx";
import * as $$$$$$11 from "./sections/BlogTemplate.tsx";
import * as $$$$$$12 from "./sections/Seo/SeoBlogPost.tsx";
import * as $$$$$$13 from "./sections/Seo/SeoBlogPostListing.tsx";
import * as $$$$$$14 from "./sections/Template.tsx";
import * as $$$$$$15 from "./sections/types.ts";

const manifest = {
  "loaders": {
    "corebiz-blog/loaders/Author.ts": $$$0,
    "corebiz-blog/loaders/Blogpost.ts": $$$4,
    "corebiz-blog/loaders/BlogPostItem.ts": $$$1,
    "corebiz-blog/loaders/BlogpostList.ts": $$$5,
    "corebiz-blog/loaders/BlogpostListing.ts": $$$6,
    "corebiz-blog/loaders/BlogPostPage.ts": $$$2,
    "corebiz-blog/loaders/BlogRelatedPosts.ts": $$$3,
    "corebiz-blog/loaders/Category.ts": $$$7,
    "corebiz-blog/loaders/ContentTypes.ts": $$$8,
    "corebiz-blog/loaders/GetCategories.ts": $$$9,
  },
  "sections": {
    "corebiz-blog/sections/Blog/components/ImageAndTextSection.tsx": $$$$$$0,
    "corebiz-blog/sections/Blog/components/ImagesSlide.tsx": $$$$$$3,
    "corebiz-blog/sections/Blog/components/ImageThreeColumnSection.tsx":
      $$$$$$1,
    "corebiz-blog/sections/Blog/components/ImageTwoColumnSection.tsx": $$$$$$2,
    "corebiz-blog/sections/Blog/components/OneImage.tsx": $$$$$$4,
    "corebiz-blog/sections/Blog/components/ProductsSection.tsx": $$$$$$5,
    "corebiz-blog/sections/Blog/components/RelatedPosts.tsx": $$$$$$6,
    "corebiz-blog/sections/Blog/components/TextSection.tsx": $$$$$$7,
    "corebiz-blog/sections/Blog/components/Video.tsx": $$$$$$8,
    "corebiz-blog/sections/BlogBannerPost.tsx": $$$$$$9,
    "corebiz-blog/sections/BlogPosts.tsx": $$$$$$10,
    "corebiz-blog/sections/BlogTemplate.tsx": $$$$$$11,
    "corebiz-blog/sections/Seo/SeoBlogPost.tsx": $$$$$$12,
    "corebiz-blog/sections/Seo/SeoBlogPostListing.tsx": $$$$$$13,
    "corebiz-blog/sections/Template.tsx": $$$$$$14,
    "corebiz-blog/sections/types.ts": $$$$$$15,
  },
  "name": "corebiz-blog",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
